name: Example GitHub Action

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello, world! This is a simple GitHub Action."
